default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=88]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --ignore=E203]
        additional_dependencies: [flake8-typing-imports==1.6.0]
-   repo: local
    hooks:
    -   id: pylint
        args: [--extension-pkg-whitelist=cv2]
        name: pylint
        entry: pylint
        language: system
        types: [python]
